/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dao.TblCategories_SE140736;
import dao.TblProducts_SE140736;
import dao.TblUsers_SE140736;
import dto.Categories_SE140736;
import dto.Products_SE140736;
import dto.Users_SE140736;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class ManagementUI_SE140736 extends javax.swing.JFrame {

    TblUsers_SE140736 listUsers = new TblUsers_SE140736();
    TblCategories_SE140736 modelCal;
    TblProducts_SE140736 modelPro;

    final int SUCCESS = 1;
    boolean addNewProduct = true;
    boolean deleteProduct = true;
    boolean addCategories = true;
    boolean deleteCategories = true;

    public ManagementUI_SE140736() throws Exception {
        initComponents();
        this.setSize(1009, 570);
        this.setLocationRelativeTo(null);

        listUsers.loadData();

        //gán mô hình hiển thị but chưa có dlieu
        modelPro = new TblProducts_SE140736();
        tblProducts.setModel(modelPro.getModelProducts());

        modelCal = new TblCategories_SE140736();
        tblCategories.setModel(modelCal.getModelCate());

        //lệnh gán nguồn cho comboBox
        try {
            cbCategoryName.setModel(new DefaultComboBoxModel<>(modelCal.getListCategoriesComboBox()));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void clearInformationCategoriesOnTable() {
        txtCateID.setText("");
        txtCateName.setText("");
        txtCateDes.setText("");
    }

    void clearInformationProductsOnTable() {
        txtProductID.setText("");
        txtProductName.setText("");
        cbCategoryName.setSelectedItem(null);
        txtUnit.setText("");
        txtQuantity.setText("");
        txtPrice.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        CategoryPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCategories = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnCateAdd = new javax.swing.JButton();
        btnCateSave = new javax.swing.JButton();
        btnCateDelete = new javax.swing.JButton();
        txtCateID = new javax.swing.JTextField();
        txtCateName = new javax.swing.JTextField();
        txtCateDes = new javax.swing.JTextField();
        ProductPanel = new javax.swing.JPanel();
        mainPart = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        detailedPart = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAddNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtProductID = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        txtUnit = new javax.swing.JTextField();
        cbCategoryName = new javax.swing.JComboBox<>();
        txtQuantity = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Login ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("User ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Password:");

        txtUserID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addComponent(jButton1)))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main Part", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 51, 204))); // NOI18N

        tblCategories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoriesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCategories);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detailed Part", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("ID:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Name:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Description:");

        btnCateAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCateAdd.setText("Add New");
        btnCateAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCateAddActionPerformed(evt);
            }
        });

        btnCateSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCateSave.setText("Save");
        btnCateSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCateSaveActionPerformed(evt);
            }
        });

        btnCateDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCateDelete.setText("Delete");
        btnCateDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCateDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnCateAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCateSave)
                        .addGap(44, 44, 44)
                        .addComponent(btnCateDelete))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCateName)
                            .addComponent(txtCateDes)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(92, 92, 92)
                        .addComponent(txtCateID, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCateDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCateAdd)
                    .addComponent(btnCateSave)
                    .addComponent(btnCateDelete))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CategoryPanelLayout = new javax.swing.GroupLayout(CategoryPanel);
        CategoryPanel.setLayout(CategoryPanelLayout);
        CategoryPanelLayout.setHorizontalGroup(
            CategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CategoryPanelLayout.setVerticalGroup(
            CategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CategoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Category", CategoryPanel);

        mainPart.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main Part", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProducts.setColumnSelectionAllowed(true);
        tblProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProducts);

        javax.swing.GroupLayout mainPartLayout = new javax.swing.GroupLayout(mainPart);
        mainPart.setLayout(mainPartLayout);
        mainPartLayout.setHorizontalGroup(
            mainPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );
        mainPartLayout.setVerticalGroup(
            mainPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        detailedPart.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detailed part:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel4.setText("Product ID:");

        jLabel5.setText("Product Name:");

        jLabel6.setText("Category Name:");

        jLabel7.setText("Unit:");

        jLabel8.setText("Quantity:");

        jLabel9.setText("Price:");

        btnAddNew.setText("Add New");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        cbCategoryName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout detailedPartLayout = new javax.swing.GroupLayout(detailedPart);
        detailedPart.setLayout(detailedPartLayout);
        detailedPartLayout.setHorizontalGroup(
            detailedPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailedPartLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(detailedPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailedPartLayout.createSequentialGroup()
                        .addComponent(btnAddNew)
                        .addGap(68, 68, 68)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete))
                    .addGroup(detailedPartLayout.createSequentialGroup()
                        .addGroup(detailedPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(detailedPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailedPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtProductName)
                                .addComponent(txtUnit)
                                .addComponent(cbCategoryName, 0, 158, Short.MAX_VALUE)
                                .addComponent(txtQuantity))
                            .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailedPartLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        detailedPartLayout.setVerticalGroup(
            detailedPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailedPartLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(detailedPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(detailedPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(detailedPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(detailedPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(detailedPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(detailedPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(detailedPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNew)
                    .addComponent(btnSave)
                    .addComponent(btnDelete))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ProductPanelLayout = new javax.swing.GroupLayout(ProductPanel);
        ProductPanel.setLayout(ProductPanelLayout);
        ProductPanelLayout.setHorizontalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(detailedPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ProductPanelLayout.setVerticalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(detailedPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Product", ProductPanel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        getContentPane().add(jPanel2, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String userID = txtUserID.getText();
        String password = String.valueOf(txtPassword.getPassword());
        if (listUsers.checkLogin(userID, password) == true) {
            JOptionPane.showMessageDialog(null, "Dang Nhap Thanh Cong");
            CardLayout layout = (CardLayout) this.getContentPane().getLayout();
            layout.next(this.getContentPane());
        } else {
            JOptionPane.showMessageDialog(null, "Dang Nhap That Bai");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductsMouseClicked
        int selectedRow = tblProducts.getSelectedRow(); //lấy dòng ng dùng đang chọn
        Products_SE140736 pro = modelPro.getModelProducts().getList().get(selectedRow); //khai báo 1 đối tượng Product

        txtProductID.setText(pro.getProductID());
        txtProductID.setEditable(false);
        txtProductName.setText(pro.getProductName());
        cbCategoryName.setSelectedItem(pro.getCategoryid() + "-" + modelCal.getListCategoriesNameComboBox(pro.getCategoryid()));
        txtUnit.setText(pro.getUnit());
        txtPrice.setText(String.valueOf(pro.getPrice()));
        txtQuantity.setText(String.valueOf(pro.getQuantity()));
//        txtQuantity.setText(pro.getQuantity() + "");
//        txtPrice.setText(pro.getPrice() + "");
        addNewProduct = false;
        deleteProduct = true;


    }//GEN-LAST:event_tblProductsMouseClicked

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        txtProductID.setEditable(true);
        clearInformationProductsOnTable();
        addNewProduct = true;
        deleteProduct = false;
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (!modelPro.validDate(txtProductID.getText().trim(),
                txtProductName.getText().trim(),
                txtUnit.getText().trim(),
                txtPrice.getText().trim(),
                txtQuantity.getText().trim(),
                cbCategoryName.getSelectedItem())) {
            return;
        }
        if (addNewProduct) {
            try {
                if (!modelPro.validDateProductID(txtProductID.getText().trim())) {
                    JOptionPane.showMessageDialog(this, "DUPLICATED CODE at " + txtProductID.getText().trim());
                    return;
                }
                Products_SE140736 pro = new Products_SE140736(txtProductID.getText().toUpperCase().trim(),
                        txtProductName.getText().trim(),
                        txtUnit.getText().trim(),
                        Float.parseFloat(txtPrice.getText().trim()),
                        Integer.parseInt(txtQuantity.getText().trim()),
                        modelPro.loadCategoriesIntoProducts(cbCategoryName.getSelectedItem().toString()));

                if (modelPro.Insert(pro) == SUCCESS) {
                    modelPro.getModelProducts().getList().add(pro);
                }
                addNewProduct = false;
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            try {
                int selectedRow = tblProducts.getSelectedRow();
                if (selectedRow < 0) {
                    JOptionPane.showMessageDialog(this, "Please Choose Row to Edit");
                }

                Products_SE140736 proOld = modelPro.getModelProducts().getList().get(selectedRow);
                Products_SE140736 proNew = new Products_SE140736(txtProductID.getText().toUpperCase().trim(),
                        txtProductName.getText().trim(),
                        txtUnit.getText().trim(),
                        Float.parseFloat(txtPrice.getText().trim()),
                        Integer.parseInt(txtQuantity.getText().trim()),
                        modelPro.loadCategoriesIntoProducts(cbCategoryName.getSelectedItem().toString()));
                if (modelPro.Save(proNew) == SUCCESS) {
//                    proOld.setProductName(proNew.getProductName());
//                    proOld.setCategoryid(proNew.getCategoryid());
//                    proOld.setUnit(proNew.getUnit());
//                    proOld.setQuantity(proNew.getQuantity());
//                    proOld.setPrice(proNew.getPrice());
                    proOld.setProductName(proNew.getProductName());
                    proOld.setUnit(proNew.getUnit());
                    proOld.setPrice(proNew.getPrice());
                    proOld.setQuantity(proNew.getQuantity());
                    proOld.setCategoryid(proNew.getCategoryid());

                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        tblProducts.updateUI();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            int selectedRow = tblProducts.getSelectedRow();
            if (selectedRow < 0 || deleteProduct == false) {
                JOptionPane.showMessageDialog(this, "Choose the Row to Delete");
                return;
            }
            int r = JOptionPane.showConfirmDialog(this, "Do you want to Delete this Products?");
            if (r == JOptionPane.YES_OPTION) {
                Products_SE140736 pro = modelPro.getModelProducts().getList().get(selectedRow);
                if (modelPro.Delete(pro) == SUCCESS) { //xóa dlieu trong database trc
                    deleteProduct = false;
                    modelPro.getModelProducts().getList().remove(pro);
                    JOptionPane.showMessageDialog(this, "Deleted");
                    clearInformationProductsOnTable();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        tblProducts.updateUI();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCateAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCateAddActionPerformed
        txtCateID.setEditable(true);
        clearInformationCategoriesOnTable();
        addCategories = true;
        deleteCategories = false;
    }//GEN-LAST:event_btnCateAddActionPerformed

    private void btnCateSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCateSaveActionPerformed
        if (!modelCal.validDate(txtCateID.getText().trim(),
                txtCateName.getText().trim(),
                txtCateDes.getText().trim())) {
            return;
        }
        if (addCategories) {
            try {
                if (!modelCal.validDateCodeCategories(txtCateID.getText().trim())) {
                    JOptionPane.showMessageDialog(this, "DUPLICATE CATEGORYID at " + txtCateID.getText().trim());
                    return;
                }
                Categories_SE140736 cate = new Categories_SE140736(txtCateID.getText().trim().toUpperCase(),
                        txtCateName.getText().trim(),
                        txtCateDes.getText().trim());

                if (modelCal.Insert(cate) == SUCCESS) {
                    modelCal.getModelCate().getList().add(cate);
                    modelCal.getListCategoriesComboBox().add(cate.getCategoryID() + "-" + cate.getCategoryName());
                }
                addCategories = false;
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            try {
                int selectedRow = tblCategories.getSelectedRow();
                if (selectedRow < 0) {
                    JOptionPane.showMessageDialog(this, "Please Choose Row to Edit!!");
                    return;
                }

                Categories_SE140736 cateNew = new Categories_SE140736(txtCateID.getText().toUpperCase().trim(),
                        txtCateName.getText().toUpperCase().trim(),
                        txtCateDes.getText().toUpperCase().trim());
                Categories_SE140736 cateOld = modelCal.getModelCate().getList().get(selectedRow);

                if (modelCal.Save(cateNew) == SUCCESS) {
                    modelCal.getListCategoriesComboBox().remove(cateOld.getCategoryID() + "-" + cateOld.getCategoryName());
                    cateOld.setCategoryName(cateNew.getCategoryName());
                    cateOld.setDescription(cateNew.getDescription());
                    modelCal.getListCategoriesComboBox().add(cateNew.getCategoryID() + "-" + cateNew.getCategoryName());
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        modelPro.getModelProducts().loadCategoriesComboBox();
        cbCategoryName.setModel(new DefaultComboBoxModel<>(modelCal.getListCategoriesComboBox()));
        tblCategories.updateUI();
    }//GEN-LAST:event_btnCateSaveActionPerformed

    private void btnCateDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCateDeleteActionPerformed
        try {
            int selectedRow = tblCategories.getSelectedRow();
            if (selectedRow < 0 || deleteCategories == false) {
                JOptionPane.showMessageDialog(this, "Choose the Row to Delete");
                return;
            }
            int r = JOptionPane.showConfirmDialog(this, "Do you want to Delete this Category?");
            if (r == JOptionPane.YES_OPTION) {
                Categories_SE140736 cate = modelCal.getModelCate().getList().get(selectedRow);

                if (!modelPro.checkConstrainCategoriesID(cate.getCategoryID())) {
                    JOptionPane.showMessageDialog(this, "Still Products is manager by this Category");
                    return;
                }
                if (modelCal.Delete(cate) == SUCCESS) { //xóa dlieu trong database trc
                    deleteCategories = false;
                    modelCal.getModelCate().getList().remove(cate);
                    modelCal.getListCategoriesComboBox().remove(cate.getCategoryID() + " - " + cate.getCategoryName());
                    JOptionPane.showMessageDialog(this, "Deleted");
                    cbCategoryName.setModel(new DefaultComboBoxModel<>(modelCal.getListCategoriesComboBox()));
                    clearInformationCategoriesOnTable();
                    modelPro.getModelProducts().loadCategoriesComboBox();
                    tblCategories.updateUI();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCateDeleteActionPerformed

    private void tblCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoriesMouseClicked
        int selectedRow = tblCategories.getSelectedRow(); //lấy dòng ng dùng đang chọn
        Categories_SE140736 cate = modelCal.getModelCate().getList().get(selectedRow); //khai báo 1 đối tượng Product

        txtCateID.setText(cate.getCategoryID());
        txtCateID.setEditable(false);
        txtCateName.setText(cate.getCategoryName());
        txtCateDes.setText(cate.getDescription());
        addNewProduct = false;
        deleteProduct = true;

    }//GEN-LAST:event_tblCategoriesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagementUI_SE140736.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagementUI_SE140736.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagementUI_SE140736.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagementUI_SE140736.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ManagementUI_SE140736().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ManagementUI_SE140736.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CategoryPanel;
    private javax.swing.JPanel ProductPanel;
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnCateAdd;
    private javax.swing.JButton btnCateDelete;
    private javax.swing.JButton btnCateSave;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbCategoryName;
    private javax.swing.JPanel detailedPart;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel mainPart;
    private javax.swing.JTable tblCategories;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtCateDes;
    private javax.swing.JTextField txtCateID;
    private javax.swing.JTextField txtCateName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtUnit;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
}
